#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/metacortex/adjustments/15-metacortex-locale.menu 1.4.7~ -- "$@"
# End automatically added section
